export default {
  products: [
    {
      _id: "1",
      name: "Zapato Lindo",
      categoria: "Zapatos",
      image: "./img/zapato.jpg",
      price: 700,
      brand: "Gucci",
      rating: 3.5,
      numReviews: 10,
      description:
        "⁣Ellas son las R O M A. Si ustedes amaban las Praga, con las Roma se enamoran :star-struck::hibiscus:Zapatillas clásicas, de ecocuero y para usar todos los días ¿Qué más podés pedir?Que dicen? Sale preventa con precio promocional? :thinking_face::sparkles:Talles del 35 al 40:high_heel:⁣⁣:truck:Envios a todo el país!⁣⁣:sparkles:Trabajamos con efectivo, transferencia bancaria, débito y crédito :credit_card:⁣",
    },
    {
      _id: "3",
      name: "Zapato Masomenos",
      image: "./img/zapato1.jpg",
      categoria: "Zapatos",
      price: 450,
      brand: "Gucci",
      rating: 3.5,
      numReviews: 10,
    },
    {
      _id: "2",
      name: "Zapato Bueno",
      categoria: "Zapatos",
      image: "./img/zapato2.jpg",
      price: 400,
      brand: "Gucci",
      rating: 3.5,
      numReviews: 10,
    },
    {
      _id: "123",
      name: "Zapato en Oferta de 40",
      categoria: "Zapatos",
      image: "./img/zapato3.jpg",
      price: 40,
      brand: "Gucci",
      rating: 3.5,
      numReviews: 10,
    },
  ],
};
