  ProductCategory[m
  ReviewModel[m
  RoutesOfProducts[m
  ShoppingCardModel[m
  categoriesModel[m
  categoryRoutes[m
  dbRelation[m
  editProduct[m
* [32mmaster[m
  productModel[m
  productRoutes[m
  storeRedux[m
  [31mremotes/origin/DBrelation[m
  [31mremotes/origin/HEAD[m -> origin/master
  [31mremotes/origin/OrderProductModel[m
  [31mremotes/origin/ProductCategory[m
  [31mremotes/origin/Productxcategories[m
  [31mremotes/origin/ReviewModel[m
  [31mremotes/origin/RoutesOfProducts[m
  [31mremotes/origin/ShoppingCardModel[m
  [31mremotes/origin/UiChanges[m
  [31mremotes/origin/UserModel[m
  [31mremotes/origin/categoriesModel[m
  [31mremotes/origin/categoryRoutes[m
  [31mremotes/origin/change-readme[m
  [31mremotes/origin/editProduct[m
  [31mremotes/origin/master[m
  [31mremotes/origin/productCard[m
  [31mremotes/origin/productComponent[m
  [31mremotes/origin/productModel[m
  [31mremotes/origin/productRoutes[m
  [31mremotes/origin/reactRouter[m
  [31mremotes/origin/searchBarComponent[m
  [31mremotes/origin/storeRedux[m
