export default {
  products: [
    {
      _id: "1",
      name: "Zapatos Borcegos",
      categoria: "Zapatos",
      image: "./img/zapato1.jpg",
      price: 700,
      rating: 3.5,
      numReviews: 10,
    },
    {
      _id: "2",
      name: "Zapatillas deportivas",
      image: "./img/zapato2.jpg",
      categoria: "Zapatos",
      price: 450,
      rating: 3.5,
      numReviews: 10,
    },
    {
      _id: "3",
      name: "Botas",
      categoria: "Zapatos",
      image: "./img/zapato3.jpg",
      price: 400,
      rating: 3.5,
      numReviews: 10,
    },
    {
      _id: "4",
      name: "Botas Bajas",
      categoria: "Zapatos",
      image: "./img/zapato4.jpg",
      price: 40,
      rating: 3.5,
      numReviews: 10,
    },
    {
      _id: "5",
      name: "Zapatos Borcegos",
      categoria: "Zapatos",
      image: "./img/zapato1.jpg",
      price: 700,
      rating: 3.5,
      numReviews: 10,
    },
    {
      _id: "6",
      name: "Zapatillas deportivas",
      image: "./img/zapato2.jpg",
      categoria: "Zapatos",
      price: 450,
      rating: 3.5,
      numReviews: 10,
    },
    {
      _id: "7",
      name: "Botas",
      categoria: "Zapatos",
      image: "./img/zapato3.jpg",
      price: 400,
      rating: 3.5,
      numReviews: 10,
    },
    {
      _id: "8",
      name: "Botas bajas",
      categoria: "Zapatos",
      image: "./img/zapato4.jpg",
      price: 40,
      rating: 3.5,
      numReviews: 10,
    },
  ],
};
